INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (525, 'Estados Unidos', 0, null, null);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (526, 'Washington', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (567, 'Oregon', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (568, 'California', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (569, 'Nevada', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (570, 'Alaska', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (571, 'Hawaii', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (572, 'Arizona', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (573, 'Utah', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (574, 'Idaho', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (575, 'New Mexico', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (576, 'Colorado', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (577, 'Wyoming', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (578, 'Montana', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (579, 'Texas', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (580, 'Oklahoma', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (581, 'Kansas', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (582, 'Nebraska', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (583, 'South Dakota', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (584, 'North Dakota', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (585, 'Lousiana', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (586, 'Arkansas', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (587, 'Missouri', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (588, 'Iowa', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (589, 'Minnesota', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (590, 'Mississippi', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (591, 'Tennessee', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (592, 'Illinois', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (593, 'Kentucky', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (594, 'Wisconsin', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (595, 'Indiana', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (596, 'Michigan', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (597, 'Ohio', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (598, 'West Virginia', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (599, 'Alabama', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (600, 'Georgia', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (601, 'Florida', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (602, 'South Carolina', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (603, 'North Carolina', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (604, 'Virginia', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (605, 'Pennsylvania', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (606, 'New York', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (607, 'District of Columbia', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (608, 'Maryland', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (609, 'Delaware', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (610, 'New Jersey', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (611, 'Connecticut', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (612, 'Rhode Island', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (613, 'Massachusetts', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (614, 'Vermont', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (615, 'New Hampshire', 1, null, 525);
INSERT INTO empresag.lugar (id, nombre, tipo, fk_nivel_socioeconomico, fk_lugar) VALUES (616, 'Maine', 1, null, 525);